In [2]:
import numpy as np
array = np.array([10,20,30,40,50])

print(array[1])
print(array[-1])

20
50


In [ ]:
print(array[1:4])

[20 30 40 50]


In [5]:
print(array[1:7])

[20 30 40 50]


In [9]:
bool_index = array>25

In [11]:
print(bool_index)


[False False  True  True  True]


In [13]:
index = [2,0,4]
print(array[index])

[30 10 50]


In [14]:
array2 = np.random.randint(1,10,size=(3,3))

In [16]:
print(array2)
print(array2[0,1])

[[8 5 3]
 [1 1 7]
 [5 7 7]]
5


In [18]:
print(array2[:2,:2])

[[8 5]
 [1 1]]


In [19]:
prices = np.array([100,200,300])
discount = np.array([0.9])
discount_prices = prices*discount
print(discount_prices)

[ 90. 180. 270.]


In [21]:
prices2 = np.random.randint(100,500,size=(3,3))
increment = np.array([10,20,30])
increment_prices = prices2+increment
print(prices2)
print(increment_prices)

[[437 490 402]
 [300 415 301]
 [302 308 185]]
[[447 510 432]
 [310 435 331]
 [312 328 215]]


In [24]:
array3 = np.array([1,2,3,4,5])
print(np.all(array3>3))

False


In [27]:
print(np.any(array3>0))

True


In [29]:
arraya = np.array([1,2,3,4,5])
arrayb = np.array([6,7,8,9,10])
concatenated = np.concatenate((arraya,arrayb))
print(concatenated)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
stacked_v = np.vstack((arraya, arrayb))
print(stacked_v)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
stacked_h = np.hstack((arraya, arrayb))
print(stacked_h)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
array_g = np.arange(1,10)
print(array_g)
split_array = np.split(array_g,3)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [35]:
survey = np.array(['bueno','excelente','malo','bueno','malo','excelente','bueno','bueno','malo','excelente'])
print(np.unique(survey))

['bueno' 'excelente' 'malo']


In [37]:
unique_elements, counts = np.unique(survey, return_counts=True)
print(unique_elements)
print(counts)

['bueno' 'excelente' 'malo']
[4 3 3]


In [40]:
array_c = np.arange(10)
view_c = array_c[1:3]
print(array_c)
print(view_c)
array_c[1:3]=[10,11]
print(array_c)
print(view_c)


[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [42]:
array_c = np.arange(10)
copy_c=array_c[[1,2]]
print(array_c)
print(copy_c)
array_c[1:3]=[10,11]
print(array_c)
print(copy_c)


[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]


In [46]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
transposed = matrix.T
print(transposed)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [47]:
array_r =np.arange(1,13)
reshaped = array_r.reshape(3,4)
print(array_r)
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
array_rv =np.arange(1,13)
reversed = array_rv[::-1]
print(array_rv)
print(reversed)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


In [50]:
matrix_f = np.reshape(array_rv,(3,4))
print(matrix_f)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
flatt = matrix_f.flatten()
print(flatt)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Operaciones basicas de algebra lineal


In [53]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [54]:
sum = A + B
print(A)
print(B)
print(sum)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [55]:
#multiplicacion
producto = np.dot(A,B)
print(producto)

[[19 22]
 [43 50]]


In [56]:
#determinante
det_A = np.linalg.det(A)
print(det_A)
inv_A = np.linalg.inv(A)
print(inv_A)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [57]:
#sistema de ecuaciones
#Ax = b
b = np.array([9,11])
x=np.linalg.solve(A,b)
print(x)

[-7.  8.]
